- README.md
GitHub is redirecting old URLs, but we might as well point to the official one.
> Adjust URL to plugin repo

- README.md
@henridf successfully brought over the file output option in https://github.com/brimsec/zinger/pull/7, but while verifying it I found there were a couple links in the README still pointing to old locations, and the README coverage was still almost exclusively focused on the Kafka/Avro use case. I've tried to bring some balance to it here by mentioning the file output option a bit more.
> Fix some links and add more coverage of file output

- cli/flags.go
- cmd/zync/etl/command.go
- cmd/zync/from-kafka/command.go
- cmd/zync/to-kafka/command.go
- etl/pool.go
- fifo/lake.go
- go.mod
- go.sum
Following Zed's lead, rename the ZED_LAKE_HOST environment variable to
ZED_LAKE and the -host flag to -lake.
> bump Zed to v0.33.0

- zavro/decoder.go
- zavro/schema.go
When decoding a union of null and a second type, zavro incorrectly
assumes that null is always the first type in the union.  Remove that
assumption.
> handle Avro union with null second type in zavro

- etl/pool.go
- fifo/lake.go
Pools have a key of kafka.offset:asc, so "head 1" in queries yields a
record with the smallest kafka.offset value.  Switch to "tail 1" to
obtain the largest.
> use "tail 1" in queries for largest kafka.offset

- cmd/zync/consume/command.go
- etl/pool.go
- fifo/lake.go
Zero isn't a good default offset for a Kafka consumer because it won't
see any messages if the topic's earliest offset is nonzero.  Use
kafka.OffsetBeginning instead.
> use kafka.OffsetBeginning where appropriate

- fifo/producer.go
Using an Avro schema's JSON encoding as its subject can produce very
long subjects, which can provoke an HTTP "414 URI Too Long" response
from the schema registry because subjects appear in some request paths.
Avoid this problem by using a hash of the corresponding ZNG type string
as a schema's subject.
> limit Avro schema subject length

- fifo/lake.go
- fifo/to.go
The command "zync to-kafka -topic T -pool P" synchronizes all records in
pool P to topic T regardless of kafka.topic, but this isn't the behavior
we want.  Restrict synchronization to records for which kafka.topic
matches T.
> filter by kafka.topic in to-kafka

- fifo/from.go
- fifo/lake.go
The "zync from-kafka" command adjusts kafka.offset in each record so it
is serialized (and thus unique) accross the entire destination pool, but
this isn't quite the behavior we want.  Serialize it separately for each
kafka.topic in the destination pool instead.
> maintain kafka.offset per topic in from-kafka

- go.mod
- zavro/schema.go
- zavro/schema_test.go
For a Zed type containing two identical records (e.g, {a:{},b:{}})
zavro.EncodeSchema returns a schema containing two records with the same
name, which is something schema registries don't allow.  Change
EncodeSchema to use avro.RecursiveSchema for any Zed record type
previously encountered so that subsequent appearances of a record type
become references (rather than duplicates) in the returned schema.
> encode repeated record as reference in zavro.EncodeSchema

- README.md
- cmd/zync/consume/command.go
- design.md
The zed command replaces zapi, and "zed serve -lake dir" replaces
"zed lake serve -R dir".
> update Zed commands

- fifo/producer.go
The io.confluent.kafka.serializers.subject.RecordNameStrategy subject
name strategy uses fully-qualified record names, so we need to do the
same here when registering a new schema with the schema registry.
> include namespace in subject when registering schema

- zavro/schema.go
- zavro/schema_test.go
zavro.EncodeSchema encodes a Zed record field with the null type as an
Avro union containing "null" twice (i.e., as ["null","null"]), but Avro
unions may not contain more than one unnamed schema of the same type.
Fix this by encoding such field as "null" rather than as a union.
> encode null field as "null" in zavro.EncodeSchema

- README.md
- demo/batch-1.zson
- demo/batch-2.zson
- demo/batch-3.zson
- demo/batch-4.zson
- demo/invoices.yaml
- etl/build.go
ETL transforms need access to Debezium event keys to produce valid JDBC
sync connector records.  Give them access to the entire event as
this.left and this.right for denorm transforms and as this.in for
stateless transforms, and change the output field to this.out for
consistency.
> adjust ETL for JDBC sync connector records

- cli/flags.go
- cli/lake.go
- cmd/zync/etl/command.go
- cmd/zync/from-kafka/command.go
- cmd/zync/to-kafka/command.go
- fifo/lake.go
Replace github.com/brimdata/zed/lake/api.OpenRemoteLake with
github.com/brimdata/zed/cli.LakeFlags.Open to allow access to non-HTTP
lakes.
> allow non-HTTP lakes

- zavro/schema.go
- zavro/schema_test.go
For a given Avro schema, JSON produced from Go by
github.com/go-avro/avro.Schema.MarshalJSON or String and from Java by
org.apache.avro.Schema.toString differs sufficiently that Apicurio
Registry's implementation of POST /subjects/{schema} does not consider
them to be the same schema.  Fix by wrapping each avro.RecordSchmea
returned by zavro.EncodeSchema with a zavro.compatReccordSchema whose
MarshalJSON and String methods emit JSON fields in the Java order.
> adjust JSON field order for Apicurio in zavro.EncodeSchema

- connectjson/connectjson.go
- connectjson/connectjson_test.go
Decode an empty Connect JSON envelope as a Zed value with type null, and
encode a Zed value with type null as an empty envelope.  (Debezium
tombstone events have a non-empty key and an empty value.)
> connectjson: handle empty envelope

- connectjson/connectjson.go
- go.mod
- go.sum
Decoder.Decode always calls json.Unmarshal and Decoder.decodeSchema, both of which are expensive.  Speed things up by calling them only if the Decoder hasn't seen the schema's JSON encoding before.
> connectjson: further improve decode performance

- connectjson/connectjson.go
- fifo/consumer.go
- zavro/decoder.go
This allows removal of some memory allocations from the decoder implementations.
> fifo: allow decoder to retain ownership of returned zed.Value

- cmd/zync/consume/command.go
- cmd/zync/from-kafka/command.go
- cmd/zync/info/command.go
- fifo/consumer.go
- go.mod
"zync from-kafka" creates a goroutine and Kafka client per Kafka topic, leading to substantial CPU and memory usage when the number of topics is large.  Reduce both by creating a single goroutine and Kafka client for all topics.
> reduce "zync from-kafka" concurrency and memory usage

- .github/workflows/ci.yaml
This version lets us pull the Go version from go.mod, so do that.
> .github/workflows: upgrade to actions/setup-go@v3

- ztests/etl-demo.yaml
brimdata/zed#4347 removes support for symlink inputs in script-style ztests.
> replace symlink with source in ztests/etl-demo.yaml

- connectjson/connectjson.go
connectjson.Decoder deliberately panics if it encounters a schema element whose name begins with org.apache.  Remove that behavior so org.apache names are allowed.
(The panic is left over from development of the connectjson package, when it wasn't clear whether to interpret values according to schema element names during decoding.  For example, a value whose corresponding schema element has type int64 and name
org.apache.kafka.connect.data.Timestamp could be interpreted either as a simple int64 or, per the name, as a time in milliseconds since the Unix epoch.  The connectjson package takes the former approach, mostly because the current decoding process offers no easy way to perform the necessary scaling.)
> Allow org.apache names in Connect JSON schema

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
Node 16 actions are deprecated so upgrade to the Node 20 versions.
(Upgrade gorelease/goreleaser-action to v5 because v6 requires changes to .goreleaser.yaml.)
> Upgrade Node 16 actions in .github/workflows
